"""
ThemeEngine — loads a TOML theme file and produces a QSS stylesheet string.

Public interface:
    ThemeEngine().load(path: str) -> str
    ThemeEngine().apply(app: QApplication, path: str) -> None
    ThemeLoadError — raised for missing or malformed theme files
"""
import toml


class ThemeLoadError(Exception):
    """Raised when a theme file cannot be loaded or parsed."""


class ThemeEngine:
    def load(self, theme_path: str) -> str:
        """
        Read a TOML theme file and return a complete QSS string.

        Raises:
            ThemeLoadError: if the file does not exist or cannot be parsed.
        """
        try:
            with open(theme_path, "r", encoding="utf-8-sig") as f:
                raw = f.read()
        except FileNotFoundError:
            raise ThemeLoadError(f"Theme file not found: {theme_path}")

        try:
            data = toml.loads(raw)
        except toml.TomlDecodeError as exc:
            raise ThemeLoadError(f"Failed to parse theme file: {exc}")

        colors = data.get("colors", {})
        fonts = data.get("fonts", {})

        return self._build_qss(colors, fonts)

    def apply(self, app, theme_path: str) -> None:
        """Load a theme and apply it to the running QApplication."""
        qss = self.load(theme_path)
        app.setStyleSheet(qss)

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _build_qss(self, colors: dict, fonts: dict) -> str:
        bg = colors.get("background", "#000000")
        surface = colors.get("surface", "#111111")
        primary = colors.get("primary", "#222222")
        accent = colors.get("accent", "#ffffff")
        text = colors.get("text", "#ffffff")
        text_muted = colors.get("text_muted", "#888888")
        border = colors.get("border", "#333333")

        family = fonts.get("family", "sans-serif")
        size_base = fonts.get("size_base", 13)
        size_small = fonts.get("size_small", 11)
        size_heading = fonts.get("size_heading", 16)

        return f"""
/* CBOSA Theme — generated by ThemeEngine */

QWidget {{
    background-color: {bg};
    color: {text};
    font-family: "{family}";
    font-size: {size_base}px;
    border: none;
}}

QMainWindow, QDialog {{
    background-color: {bg};
}}

QDockWidget {{
    background-color: {surface};
    color: {text};
    font-size: {size_base}px;
}}

QDockWidget::title {{
    background-color: {primary};
    color: {text};
    padding: 4px 8px;
    font-size: {size_small}px;
}}

QPushButton {{
    background-color: {primary};
    color: {text};
    border: 1px solid {border};
    padding: 4px 12px;
    font-size: {size_base}px;
}}

QPushButton:hover {{
    background-color: {accent};
}}

QLineEdit, QTextEdit, QPlainTextEdit {{
    background-color: {surface};
    color: {text};
    border: 1px solid {border};
    font-family: "{family}";
    font-size: {size_base}px;
    padding: 2px 4px;
}}

QTreeView, QListView, QTableView {{
    background-color: {surface};
    color: {text};
    border: 1px solid {border};
    alternate-background-color: {bg};
}}

QTreeView::item:selected, QListView::item:selected, QTableView::item:selected {{
    background-color: {accent};
    color: {text};
}}

QMenuBar {{
    background-color: {surface};
    color: {text};
}}

QMenuBar::item:selected {{
    background-color: {primary};
}}

QMenu {{
    background-color: {surface};
    color: {text};
    border: 1px solid {border};
}}

QMenu::item:selected {{
    background-color: {accent};
}}

QScrollBar:vertical, QScrollBar:horizontal {{
    background-color: {surface};
    border: none;
    width: 8px;
    height: 8px;
}}

QScrollBar::handle:vertical, QScrollBar::handle:horizontal {{
    background-color: {border};
    border-radius: 4px;
}}

QLabel {{
    color: {text};
    font-size: {size_base}px;
}}

QLabel[heading="true"] {{
    font-size: {size_heading}px;
    color: {text};
}}

QLabel[muted="true"] {{
    color: {text_muted};
    font-size: {size_small}px;
}}

QSplitter::handle {{
    background-color: {border};
}}

QStatusBar {{
    background-color: {surface};
    color: {text_muted};
    font-size: {size_small}px;
}}
""".strip()
